name: honeybee-events
region: sgp  # Singapore - optimal for Asia-based users

# Database
databases:
  - name: honeybee-db
    engine: PG
    production: true
    version: "16"

# Backend API Service
services:
  - name: api
    github:
      repo: YOUR_GITHUB_USERNAME/honeybee
      branch: main
      deploy_on_push: true
    source_dir: /server
    build_command: npm install
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001

    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${honeybee-db.DATABASE_URL}
      - key: CLIENT_URL
        scope: RUN_TIME
        value: ${_self.PUBLIC_URL}
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: CHANGE_THIS_TO_RANDOM_STRING

    health_check:
      http_path: /api/auth/health

# Frontend Static Site
static_sites:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/honeybee
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: dist

    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${api.PUBLIC_URL}/api

# Allow WebSocket connections
features:
  - buildpack-stack=ubuntu-22
